version: '3.5' 

services: 

    back: 
      build: ./backend-example-docker-master 
      ports: 
        - 8000:8000
      container_name: back
      environment: 
        - API_URL=http://localhost:5000
        - REDIS=cache
        - REDIS_PORT=6379
    cache:
      image: redis
    front:
        build: ./frontend-example-docker-master 
        ports: 
          - 5000:5000
        container_name: front
        environment: 
          - API_URL=http://localhost:8000
         