version: '3.5' 

services: 
  
    back: 
      build: ./backend-example-docker-master 
      ports: 
        - 8000:8000
      container_name: back
      depends_on: 
        - db
      environment: 
        - FRONT_URL=http://localhost:5000
        - REDIS=redis
        - DB_USERNAME=user
        - DB_PASSWORD=pass
        - DB_HOST=db  
    db:
      image: postgres
      restart: unless-stopped
      environment: 
        - POSTGRES_USER=user
        - POSTGRES_PASSWORD=pass
      volumes:
        - database:/var/lib/postgresql/data
    front:
        build: ./frontend-example-docker-master 
        ports: 
          - 5000:5000
        container_name: front
        environment: 
          - API_URL=http://localhost:8000
    redis:
      image: redis
      volumes:
        - redis:/data    
volumes:
  database:
  redis:
